name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Cambia "main" por tu rama principal si es diferente

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Desplegar a GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ # Cambia esto a la carpeta que contiene tu sitio (por ejemplo, 'dist' si construyes)
